archlinux: disable sandbox due to missing kernel landlock
This fixes the following error.
error: restricting filesystem access failed because landlock is not supported by the kernel!

copy-pasta https://gitlab.archlinux.org/archlinux/archlinux-docker/-/commit/ae0527df18a9c5b94b28351b2265a20012d2fda0